[package]
name = "w3p-hwm"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
tokio = { version = "1.48", features = ["rt", "macros", "signal", "time"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls"] }
urlencoding = "2.1"
sysinfo = "0.37"
get_if_addrs = "0.5"
hostname = "0.4"
image = { version = "0.25", default-features = false, features = ["png"] }
imageproc = { version = "0.25", default-features = false }
ab_glyph = "0.2"
chrono = { version = "0.4", default-features = false, features = ["clock"] }
spidev = "0.7"
gpiocdev = "0.8"

[profile.release]
lto = true
codegen-units = 1
strip = true

[lints.clippy]
mod_module_files = "deny"
