name: Build PR Dashboard Artifact

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build-pr-artifact:
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up mise
        uses: jdx/mise-action@v2

      - name: Install build tools
        run: |
          mise install

      - name: Build release binary
        run: |
          mise run build-aarch64

      - name: Prepare PR artifact
        run: |
          mkdir web3-pi-dashboard-bin
          cp target/aarch64-unknown-linux-gnu/release/w3p-hwm web3-pi-dashboard-bin/hwmonitor
          chmod +x web3-pi-dashboard-bin/hwmonitor
          cp -r font/ web3-pi-dashboard-bin/
          cp -r img/ web3-pi-dashboard-bin/
          zip -r web3-pi-dashboard-bin.zip web3-pi-dashboard-bin/

      - name: Upload PR artifact
        uses: actions/upload-artifact@v4
        with:
          name: web3-pi-dashboard-bin
          path: web3-pi-dashboard-bin.zip
          if-no-files-found: error
